//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQuoteMedia
    {
        public int Id { get; set; }
        public int JobQuoteId { get; set; }
        public string FileName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual JobQuote JobQuote { get; set; }
    }
}
