//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeysEntities : DbContext
    {
        public KeysEntities()
            : base("name=KeysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobQuote> JobQuote { get; set; }
        public virtual DbSet<JobQuoteMedia> JobQuoteMedia { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<LoginClaim> LoginClaim { get; set; }
        public virtual DbSet<LoginRole> LoginRole { get; set; }
        public virtual DbSet<LoginSocialMedia> LoginSocialMedia { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<ManagerProperty> ManagerProperty { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<MediaType> MediaType { get; set; }
        public virtual DbSet<OwnerProperty> OwnerProperty { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<OwnershipStatus> OwnershipStatus { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<PropertyExpense> PropertyExpense { get; set; }
        public virtual DbSet<PropertyFinance> PropertyFinance { get; set; }
        public virtual DbSet<PropertyHomeValue> PropertyHomeValue { get; set; }
        public virtual DbSet<PropertyHomeValueType> PropertyHomeValueType { get; set; }
        public virtual DbSet<PropertyMedia> PropertyMedia { get; set; }
        public virtual DbSet<PropertyRentalPayment> PropertyRentalPayment { get; set; }
        public virtual DbSet<PropertyRepayment> PropertyRepayment { get; set; }
        public virtual DbSet<PropertyRequest> PropertyRequest { get; set; }
        public virtual DbSet<PropertyRequestMedia> PropertyRequestMedia { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<RentalApplication> RentalApplication { get; set; }
        public virtual DbSet<RentalApplicationMedia> RentalApplicationMedia { get; set; }
        public virtual DbSet<RentalApplicationStatus> RentalApplicationStatus { get; set; }
        public virtual DbSet<RentalListing> RentalListing { get; set; }
        public virtual DbSet<RentalListingMedia> RentalListingMedia { get; set; }
        public virtual DbSet<RentalListingStatus> RentalListingStatus { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<RequestType> RequestType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProvider { get; set; }
        public virtual DbSet<ServiceProviderJobStatus> ServiceProviderJobStatus { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TargetRentType> TargetRentType { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<TenantJobRequest> TenantJobRequest { get; set; }
        public virtual DbSet<TenantJobRequestMedia> TenantJobRequestMedia { get; set; }
        public virtual DbSet<TenantJobStatus> TenantJobStatus { get; set; }
        public virtual DbSet<TenantMedia> TenantMedia { get; set; }
        public virtual DbSet<TenantPaymentFrequencies> TenantPaymentFrequencies { get; set; }
        public virtual DbSet<TenantProperty> TenantProperty { get; set; }
        public virtual DbSet<XeroTokenStore> XeroTokenStore { get; set; }
        public virtual DbSet<Login_Deleted> Login_Deleted { get; set; }
        public virtual DbSet<JobMedia> JobMedia { get; set; }
        public virtual DbSet<RequestReply> RequestReply { get; set; }
        public virtual DbSet<RequestReplyMedia> RequestReplyMedia { get; set; }
        public virtual DbSet<TenantPropertyLiability> TenantPropertyLiability { get; set; }
        public virtual DbSet<InspectionStatus> InspectionStatus { get; set; }
        public virtual DbSet<InspectionMedia> InspectionMedia { get; set; }
        public virtual DbSet<PersonMedia> PersonMedia { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<JobWatchList> JobWatchList { get; set; }
        public virtual DbSet<RentalWatchList> RentalWatchList { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<UserRating> UserRating { get; set; }
        public virtual DbSet<MessageDeliveryType> MessageDeliveryType { get; set; }
        public virtual DbSet<MessageType> MessageType { get; set; }
        public virtual DbSet<OutGoingMessage> OutGoingMessage { get; set; }
        public virtual DbSet<RentalPaymentTracking> RentalPaymentTracking { get; set; }
    }
}
