//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRole
    {
        public int PersonId { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public bool PendingApproval { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Person Person { get; set; }
    }
}
