//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutGoingMessage
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int MessageTypeId { get; set; }
        public int DeliveryTypeId { get; set; }
        public string TargetAddress { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public string Error { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MessageDeliveryType MessageDeliveryType { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual Person Person { get; set; }
    }
}
