//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerProperty
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int PropertyId { get; set; }
        public int OwnershipStatusId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Owners Owners { get; set; }
        public virtual OwnershipStatus OwnershipStatus { get; set; }
        public virtual Person Person { get; set; }
        public virtual Property Property { get; set; }
    }
}
