//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyFinance
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Mortgage { get; set; }
        public Nullable<decimal> TotalRepayment { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public Nullable<decimal> CurrentHomeValue { get; set; }
        public Nullable<decimal> CapitalGain { get; set; }
        public Nullable<decimal> ActualRentalPayments { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
