//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyRequest()
        {
            this.PropertyRequestMedia = new HashSet<PropertyRequestMedia>();
            this.RequestReply = new HashSet<RequestReply>();
            this.Inspection = new HashSet<Inspection>();
        }
    
        public int Id { get; set; }
        public int RequestTypeId { get; set; }
        public int PropertyId { get; set; }
        public bool ToOwner { get; set; }
        public bool ToTenant { get; set; }
        public string RequestMessage { get; set; }
        public int RequestStatusId { get; set; }
        public bool IsViewed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> RecipientId { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual RequestType RequestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRequestMedia> PropertyRequestMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestReply> RequestReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
    }
}
