//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Job = new HashSet<Job>();
            this.ManagerProperty = new HashSet<ManagerProperty>();
            this.OwnerProperty = new HashSet<OwnerProperty>();
            this.PropertyExpense = new HashSet<PropertyExpense>();
            this.PropertyHomeValue = new HashSet<PropertyHomeValue>();
            this.PropertyMedia = new HashSet<PropertyMedia>();
            this.PropertyRequest = new HashSet<PropertyRequest>();
            this.RentalListing = new HashSet<RentalListing>();
            this.PropertyRentalPayment = new HashSet<PropertyRentalPayment>();
            this.PropertyRepayment = new HashSet<PropertyRepayment>();
            this.TenantProperty = new HashSet<TenantProperty>();
            this.TenantJobRequest = new HashSet<TenantJobRequest>();
            this.JobMedia = new HashSet<JobMedia>();
            this.Inspection = new HashSet<Inspection>();
        }
    
        public int Id { get; set; }
        public int PropertyTypeId { get; set; }
        public int AddressId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Bedroom { get; set; }
        public Nullable<int> Bathroom { get; set; }
        public Nullable<double> LandSqm { get; set; }
        public Nullable<int> ParkingSpace { get; set; }
        public Nullable<double> FloorArea { get; set; }
        public Nullable<decimal> TargetRent { get; set; }
        public int TargetRentTypeId { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> HasCompany { get; set; }
        public Nullable<bool> IsOwnerOccupied { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerProperty> ManagerProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerProperty> OwnerProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyExpense> PropertyExpense { get; set; }
        public virtual PropertyFinance PropertyFinance { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual TargetRentType TargetRentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyHomeValue> PropertyHomeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMedia> PropertyMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRequest> PropertyRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalListing> RentalListing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRentalPayment> PropertyRentalPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRepayment> PropertyRepayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantProperty> TenantProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantJobRequest> TenantJobRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobMedia> JobMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
        public virtual Address Address { get; set; }
    }
}
