//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentalListing()
        {
            this.RentalApplication = new HashSet<RentalApplication>();
            this.RentalListingMedia = new HashSet<RentalListingMedia>();
            this.RentalWatchList = new HashSet<RentalWatchList>();
        }
    
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MovingCost { get; set; }
        public decimal TargetRent { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string Furnishing { get; set; }
        public string IdealTenant { get; set; }
        public Nullable<int> OccupantCount { get; set; }
        public string PetsAllowed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public int RentalStatusId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalApplication> RentalApplication { get; set; }
        public virtual RentalListingStatus RentalListingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalListingMedia> RentalListingMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalWatchList> RentalWatchList { get; set; }
    }
}
