//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantJobRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TenantJobRequest()
        {
            this.JobQuote = new HashSet<JobQuote>();
            this.TenantJobRequestMedia = new HashSet<TenantJobRequestMedia>();
            this.JobWatchList = new HashSet<JobWatchList>();
        }
    
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int PropertyId { get; set; }
        public string JobDescription { get; set; }
        public int JobStatusId { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<decimal> MaxBudget { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobQuote> JobQuote { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Property Property { get; set; }
        public virtual TenantJobStatus TenantJobStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantJobRequestMedia> TenantJobRequestMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWatchList> JobWatchList { get; set; }
    }
}
