//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroTokenStore
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string OrganisationId { get; set; }
        public string TokenType { get; set; }
        public string TokenKey { get; set; }
        public string TokenSecret { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public string Session { get; set; }
        public Nullable<System.DateTime> SessionExpiresAt { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
